import { Injectable } from '@angular/core';
import { Product } from '../models/index';

@Injectable({
  providedIn: 'root'
})
export class InMemoryDataService implements InMemoryDataService {
  createDb() {
    const products: Product[] = 
    [
      {
        "id": 1000,
        "code": "f230fh0g3",
        "name": "Bamboo Watch",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 65,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 5
      ,"quantity": 10  },
        {
        "id": 1001,
        "code": "nvklal433",
        "name": "Black Watch",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 72,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1002,
        "code": "zz21cz3c1",
        "name": "Blue Band",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 79,
        "category": "Fitness",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 3
      ,"quantity": 2  },
        {
        "id": 1003,
        "code": "244wgerg2",
        "name": "Blue T-Shirt",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 29,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 5
      ,"quantity": 3  },
        {
        "id": 1004,
        "code": "h456wer53",
        "name": "Bracelet",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 15,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 10  },
        {
        "id": 1005,
        "code": "av2231fwg",
        "name": "Brown Purse",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 120,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "OUTOFSTOCK",
        "rating": 4
      ,"quantity": 5  },
        {
        "id": 1006,
        "code": "bib36pfvm",
        "name": "Chakra Bracelet",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 32,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 3
      ,"quantity": 3  },
        {
        "id": 1007,
        "code": "mbvjkgip5",
        "name": "Galaxy Earrings",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 34,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 5
      ,"quantity": 1  },
        {
        "id": 1008,
        "code": "vbb124btr",
        "name": "Game Controller",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 99,
        "category": "Electronics",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1009,
        "code": "cm230f032",
        "name": "Gaming Set",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 299,
        "category": "Electronics",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 3
      ,"quantity": 1  },
        {
        "id": 1010,
        "code": "plb34234v",
        "name": "Gold Phone Case",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 24,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "OUTOFSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1011,
        "code": "4920nnc2d",
        "name": "Green Earbuds",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 89,
        "category": "Electronics",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1012,
        "code": "250vm23cc",
        "name": "Green T-Shirt",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 49,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 5
      ,"quantity": 1  },
        {
        "id": 1013,
        "code": "fldsmn31b",
        "name": "Grey T-Shirt",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 48,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "OUTOFSTOCK",
        "rating": 3
      ,"quantity": 1  },
        {
        "id": 1014,
        "code": "waas1x2as",
        "name": "Headphones",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 175,
        "category": "Electronics",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 5
      ,"quantity": 1  },
        {
        "id": 1015,
        "code": "vb34btbg5",
        "name": "Light Green T-Shirt",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 49,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1016,
        "code": "k8l6j58jl",
        "name": "Lime Band",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 79,
        "category": "Fitness",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 3
      ,"quantity": 1  },
        {
        "id": 1017,
        "code": "v435nn85n",
        "name": "Mini Speakers",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 85,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1018,
        "code": "09zx9c0zc",
        "name": "Painted Phone Case",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 56,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 5
      ,"quantity": 1  },
        {
        "id": 1019,
        "code": "mnb5mb2m5",
        "name": "Pink Band",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 79,
        "category": "Fitness",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1020,
        "code": "r23fwf2w3",
        "name": "Pink Purse",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 110,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "OUTOFSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1021,
        "code": "pxpzczo23",
        "name": "Purple Band",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 79,
        "category": "Fitness",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 3
      ,"quantity": 1  },
        {
        "id": 1022,
        "code": "2c42cb5cb",
        "name": "Purple Gemstone Necklace",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 45,
        "category": "Accessories",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1023,
        "code": "5k43kkk23",
        "name": "Purple T-Shirt",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 49,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 5
      ,"quantity": 1  },
        {
        "id": 1024,
        "code": "lm2tny2k4",
        "name": "Shoes",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 64,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1025,
        "code": "nbm5mv45n",
        "name": "Sneakers",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 78,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 4
      ,"quantity": 1  },
        {
        "id": 1026,
        "code": "zx23zc42c",
        "name": "Teal T-Shirt",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 49,
        "category": "Clothing",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "LOWSTOCK",
        "rating": 3
      ,"quantity": 1  },
        {
        "id": 1027,
        "code": "acvx872gc",
        "name": "Yellow Earbuds",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 89,
        "category": "Electronics",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 3
      ,"quantity": 1  },
        {
        "id": 1028,
        "code": "tx125ck42",
        "name": "Yoga Mat",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 20,
        "category": "Fitness",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 5
      ,"quantity": 1  },
        {
        "id": 1029,
        "code": "gwuby345v",
        "name": "Yoga Set",
        "description": "Product Description",
        "image": "../assets/img/bamboo-watch.png",
        "price": 20,
        "category": "Fitness",
        "createdAt": 1718114215761,
        "updatedAt": 1718114215761,
        "shellId": 15,
        "internalReference": "REF-123-456",
        "inventoryStatus": "INSTOCK",
        "rating": 8,
        "quantity": 8
      }
    ]
    
    return { products };
  }
}
